const INPUT_CHANGE = 'INPUT_CHANGE';
const LIST_ADD = 'LIST_ADD';
const LIST_DEL = 'LIST_DEL';
const INIT_LIST_DATA = 'INIT_LIST_DATA';
const GET_INIT_LIST = 'GET_INIT_LIST';

export {INPUT_CHANGE,LIST_ADD,LIST_DEL,INIT_LIST_DATA,GET_INIT_LIST}

// 这个保存一个types 配置 统一使用